
---
apiVersion: db.janikgar.lan/v1alpha1
kind: Postgres
metadata:
  labels:
    app.kubernetes.io/name: operator-sandbox
    app.kubernetes.io/managed-by: kustomize
  name: blue
spec:
  role: Primary
---
apiVersion: db.janikgar.lan/v1alpha1
kind: Postgres
metadata:
  labels:
    app.kubernetes.io/name: operator-sandbox
    app.kubernetes.io/managed-by: kustomize
  name: green
spec:
  role: Replica
  source: blue
